### PR TITLE
Adding support for bicep v0.22.6

### PR DESCRIPTION
**Pull request by PalmEmanuel**
# Pull Request

### Added
- Support for Bicep v0.22.6

### Changed
- Version changed to 2.3.0

## Task list

- [X] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [ ] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [X] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Markdown help added/updated.
- [ ] Unit tests added/updated.

### CODE REVIEW

**Comment by PalmEmanuel** [comment]
`Export-BicepNetResource` has broken between the versions.

image

```plaintext
   at Bicep.Core.Workspaces.SourceFileGroupingBuilder.Build(Uri entryFileUri, IFeatureProviderFactory featuresFactory, ImmutableHashSet`1 sourceFilesToRebuild) in E:\GitHub\Bicep\BicepNet\output\RequiredModules\Bicep\Bicep\src\Bicep.Core\Workspaces\SourceFileGroupingBuilder.cs:line 100
   at Bicep.Core.Workspaces.SourceFileGroupingBuilder.Build(IFileResolver fileResolver, IModuleDispatcher moduleDispatcher, IReadOnlyWorkspace workspace, Uri entryFileUri, IFeatureProviderFactory featuresFactory, Boolean forceModulesRestore) in E:\GitHub\Bicep\BicepNet\output\RequiredModules\Bicep\Bicep\src\Bicep.Core\Workspaces\SourceFileGroupingBuilder.cs:line 65
   at BicepNet.Core.BicepWrapper.RewriteBicepTemplate(String template) in E:\GitHub\Bicep\BicepNet\BicepNet.Core\BicepWrapper.ConvertResourceToBicep.cs:line 30
   at BicepNet.Core.BicepWrapper.ExportResourceAsync(String id, String configurationPath, Boolean includeTargetScope) in E:\GitHub\Bicep\BicepNet\BicepNet.Core\BicepWrapper.ExportResource.cs:line 64
   at BicepNet.Core.BicepWrapper.ExportResourcesAsync(String[] ids, String configurationPath, Boolean includeTargetScope) in E:\GitHub\Bicep\BicepNet\BicepNet.Core\BicepWrapper.ExportResource.cs:line 24
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at BicepNet.Core.BicepWrapper.ExportResources(String[] ids, String configurationPath, Boolean includeTargetScope) in E:\GitHub\Bicep\BicepNet\BicepNet.Core\BicepWrapper.ExportResource.cs:line 14
   at BicepNet.PS.Commands.ExportBicepNetResourceCommand.ProcessRecord() in E:\GitHub\Bicep\BicepNet\BicepNet.PS\Commands\ExportBicepNetResourceCommand.cs:line 19
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

**Comment by PalmEmanuel** [comment]
`Restore-BicepNetFile` has also changed internally since last version where it works as intended. It still seems to restore modules, but implies that it didn't find any modules even after successfully restoring them.

image

We'll have to find a new of figuring out which modules were restored.

**Comment by PalmEmanuel** [comment]
`Set-BicepNetCredential` or `Get-BicepNetAccessToken` seems to not work anymore, even in currently released version.

We should probably rework these completely with [AzAuth](https://github.com/PalmEmanuel/AzAuth/) anyway now that it has full support for tokencache persistence, so I suggest we go ahead with this PR without poking at those.

**Comment by PalmEmanuel** [comment]
Everything compiles and all commands seem to be working when testing manually.

No new features implemented yet from Bicep, but the PR is ready for a review now!

**Review by SimonWahlin — APPROVED** [review]
Looks good and works with all tests in PSBicep

**Pull request merged**
