### PR TITLE
Support for Bicep version 0.6.1

### PR DESCRIPTION
**Pull request by PalmEmanuel**
Support for Version 0.6.1. This PR replaces #29.

Co-authored-by: Jens Nilsson <jens_nill@hotmail.com>

### CODE REVIEW

**Comment by StefanIvemo** [comment]
The Bicep version 0.6.1 had a bug that caused issues with authentication to ACR. A new release is out: https://github.com/Azure/bicep/releases/tag/v0.6.11

**Comment by StefanIvemo** [comment]
And another bug fix https://github.com/Azure/bicep/releases/tag/v0.6.18

**Comment by StefanIvemo** [comment]
All PSBicep test passes with this PR. Will do some manual integration tests for Publish and Restore commands.

**Comment by StefanIvemo** [comment]
Bumped the version to v0.6.18 when testing and it seems to work fine without changes to this PR.

**Comment by PalmEmanuel** [comment]
It seems to work fine with the new version v0.6.18 as you say, so I went ahead and bumped the version in this PR.

**Review by StefanIvemo — APPROVED** [review]

**Pull request merged**
