### PR TITLE
New command to get the used config for a scenario

### LINKED ISSUE #34: New command to find which bicepconfig.json file is used
BicepNet issue mirror for https://github.com/PSBicep/PSBicep/issues/263.

### PR DESCRIPTION
**Pull request by PalmEmanuel**
- New command Get-BicepNetConfig, closes #34
- Dependency script change to allow for preview versions of .NET
- Version bump

### CODE REVIEW

**Comment by PalmEmanuel** [comment]
See if `Get-BicepNetConfig` matches the expectations. It needs a path, and returns an object with two properties:

- `Path` - The path to the .bicep file to use for finding the config to use, or "Default" if no bicepconfig.json was found.
- `Config` - The contents of the configuration. Not sure if we want to expose this for the user ([Bicep CLI specifically has a comment in their version of the file regarding this](https://github.com/Azure/bicep/blob/main/src/Bicep.Core/Configuration/bicepconfig.json#L2)), and if we do we should maybe consider returning the "fully merged" configuration if the user has only provided a partial config file (such as only specified the module registry parts).

**Comment by StefanIvemo** [comment]
> * and if we do we should maybe consider returning the "fully merged" configuration if the user has only provided a partial config file (such as only specified the module registry parts).

I like the idea of returning the fully merged config. It makes sense to show the current config.

**Comment by StefanIvemo** [comment]
Works great! Is it stupid to add a `-Default` switch? At least I would like to have the option to get the default config in a simple way.

**Comment by PalmEmanuel** [comment]
Have a look at the changes now! I added a `-Default` switch, which is not mandatory (so you can run just `Get-BicepNetConfig` on its own), and the output is now merged with the default config, so you always see the full configuration of your command.

**Comment by StefanIvemo** [comment]
After offline discussions:

- Add `-Scope` parameter with `local, default and merged`  as allowed values

**Comment by PalmEmanuel** [comment]
The `-Default` parameter is now replaced by `-Scope` which allows three different values.

- `Default` - Gets the built-in configuration.
- `Merged` - Combines any found configuration file with the built-in configuration.
- `Local` - Gets only the configuration from a found configuration file.

Running only `Get-BicepNetConfig` will set the scope to `Default`. Running `Get-BicepNetConfig` with the `-Path` parameter will set the scope to `Merged`.

**Review by StefanIvemo — APPROVED** [review]

**Pull request merged**
