### PR TITLE
Publish and Restore implemented

### PR DESCRIPTION
**Pull request by PalmEmanuel**
New commands to support `bicep publish` and `bicep restore`. Also added `NoRestore` parameter to `Build-BicepNetFile` Wrapper module now looks like the following:
```PowerShell
Build-BicepNetFile -Path <string> [-NoRestore] [<CommonParameters>]

ConvertTo-BicepNetFile -Path <string> [<CommonParameters>]

Get-BicepNetVersion [<CommonParameters>]

Publish-BicepNetFile -Path <string> -Target <string> [<CommonParameters>]

Restore-BicepNetFile -Path <string> [<CommonParameters>]
```

### CODE REVIEW

**Comment by PalmEmanuel** [comment]
Also refactored a majority of the setup code that is shared to be defined in BicepWrapper.cs and utilized in the partial class "command" files.

**Comment by StefanIvemo** [comment]
Tested restore and publish and they work as expected.

**Comment by StefanIvemo** [comment]
Can you change the version number in `.bicepVersion` to v0.4.1008 as while we are at it?

**Comment by StefanIvemo** [comment]
LGTM! I think we should merge and release a new version of BicepNet. ping @SimonWahlin

**Comment by SimonWahlin** [comment]
Great!

I'll get on that.

**Comment by PalmEmanuel** [comment]
Versions bumped to v0.4.1008 for Bicep and 1.0.6 for BicepNet.

**Pull request merged**
